env:
  global:
  - secure: wFiCnIcF1zwna95Y60Jy+hsHzezCxjpP04AhiHuHTuxelnMQBdBTd9l/Rk7d/nOd8kDMCrtFJzmN6tpABdtlO+lkHcqKbyZlohoh81PuSxFFMaPGCHmeynem2PUyIcHD3BnYp7VbcXNrV8tZwemjNhuEd+xyWKAuXgQsyvmahrWpXC4caeejFzbge/QveN0DULgFAKVMhawisK/RGbr1EnqmDuEHX1/SXN/t9HJLr+zA9HW7FE44GdbQV+pjtbYi/csqLpdja89SJlwRIgu4lUH9zrZX3xIH06WXxmIv8dUS83rZ00nArKtHsLbP/zu+thDyShSEE4a0m8BDKfVQ9iFc4XrRgdhhmDQW7f/4uXuSwY+ysYPi9+JPAyYkHkZQHE11zP6bKde6+SaRdqqDcTr6lBv7CwxbQbAXAkx4BhHu5n5YFxcjE9KTi8G9TFGEbeHlZxrZ6SOaXuEqRlNVvhExzTUQE264ePBLQwcroSbNfBkECcZFroEI2jBzMt0HqR9JCfL4qtDpoqXuP14dSvpASnMeAE+8Titxs+LsEMjM4Mc63wkOFOMXDs4gyeeCqiZ7ed3egYd3qJwPwR+kYfSbqI/My7IeVG00ABJiS7vjZakNlf7We6eTlh+zova/DDJIiZeQNLOX6LFctpQSUq5SP+C3EC9xazxykq6iLlw=
  - secure: nQIbWv3fLt6cdUaCF62lgN9eiBp2ClMbJefiz8F4omu6TRwp1CPWgJBiEucXVfy6IRAcGfi0JhNu12zw1hw9tqVJUxZpPl3Mi+mjDlNBenR519ca6ZHlDCOzYSPqtcB2v23uk27p5g6no58YjKHfo3oa5MnYBM0z26VBAE71tWZEm6PlfVrJFuOif9OfPbAYsM35/BJjb1Wfx6PLjNoh1qL0+pKUWyoRCATYWNNaaxPebpzNAqagCPgPLcgUVPtZgBkChx3LOl8du0zFnYUsmBc0o0i/3efOXJbf6/yxmEHA094kCD7qGIPa8wxC8fYEkBzEr41luuG4dfRI3vzthoR+HVU3LS0uE8Zpd5VP4+h3AHAo8WcxF0ZfOdc6+m8eugE880ZXPiGCTMV6DU3LscjbLzY+jphfKMwfjym//+YXm+dCorZtlChBSWl0KGSqsXdEzN5MfiE4rYISGYGFdR4WCKAU/CRNjT+8flxSea8EIZTP1zKPdEULu9SNu41G3Z6SCy0zqoB+Sh9qU0YkDWMjIZtS+3KBhx+8BCYZ7X4YRRaHDZZGV/j/SIUBJVtKkSHivHDXkPJspAv8wzVygEIJgH/D63sP67YuFgCvMWU/W7Pj/I7YJJcLB4UwrEwiXhemgF38wb+W2otjwK1/vCJUSItMWyHJtduqwN3tEVc=

sudo: false

rvm:
  - "2.1.0"
node_js:
  - "0.10"

branches:
  only:
    - master

before_install: npm install -g grunt-cli

install:
  - npm install
  - bundle install --deployment --jobs=3 --retry=3

cache:
  directories:
    - vendor/bundle
    - node_modules

script: grunt build

after_success:
  - bundle exec s3_website push
